// Generated by https://quicktype.io

export interface Country {
    flags:        Flags;
    name:         Name;
    cca2:         string;
    cca3:         string;
    capital:      string[];
    altSpellings: string[];
    population:   number;
    translations: Translations;
    languages:    any;
    currencies:   any;
}

export interface Flags {
    png: string;
    svg: string;
}

export interface Name {
    common:     string;
    official:   string;
    nativeName: any;
}

export interface Translations {
    spa: any;
    por: any;
    fra: any;
    ita: any;
    deu: any;
    jpn: any;
    kor: any;
 }