// Generated by https://quicktype.io

export interface Country {
    flags:        Flags;
    name:         Name;
    cca2:         string;
    capital:      string[];
    altSpellings: string[];
    population:   number;
    translations: Translations;
    languages:    any;
    currencies:   any;
}

export interface Flags {
    png: string;
    svg: string;
}

export interface Name {
    common:     string;
    official:   string;
    nativeName: any;
}

export interface Translations {
    de: string;
    es: string;
    fr: string;
    ja: string;
    it: string;
    br: string;
    pt: string;
    nl: string;
    hr: string;
    fa: string;
 }